version: '3'
services:
  node-app:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8787:8787"
    command: ["sh", "-c", "npm install && node app.js"]

  nginx:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node-app
