version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./ssl/cert.pem:/etc/ssl/cert.pem
      - ./ssl/key.pem:/etc/ssl/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "8080"
      - "443:443"
    depends_on:
      - node-app
    environment:
      - NGINX_PORT=${NGINX_PORT}  # Variable de entorno para NGINX
      - SSL_PORT=${SSL_PORT}  # Variable de entorno para NGINX
      #   - ANOTHER_VARIABLE=valor  # Otra variable de entorno para NGINX
      #   - NGINX_CUSTOM_VARIABLE=valor_personalizado  # Tu variable de entorno
