version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./ssl/cert.pem:/etc/ssl/cert.pem
      - ./ssl/key.pem:/etc/ssl/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node-app-2
    environment:
      - NGINX_PORT=${NGINX_PORT}  # Variable de entorno para NGINX
      - SSL_PORT=${SSL_PORT}  # Variable de entorno para NGINX
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
      
# docker run -d --network=my-network --name node-app-2 -p 8788:2222 mi-app
#-h mi_nombre_de_contenedor

# docker run --rm --network=my-network alpine nslookup mi-contenedor-ejecutado
